version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flighttracking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    init: true
    volumes:
      - ./db_data:/var/lib/postgresql/data
        # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        # - ./test_data.sql:/docker-entrypoint-initdb.d/test_data.sql

  app:
    build: .
    environment:
      DB_TYPE: postgresql  # Change this to mysql or sqlite if needed
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: flighttracking
      DATABASE_URL: postgresql://user:password@db:5432/flighttracking
    init: true
    volumes:
      - ./ui/dist:/webapp
    ports:
      - "7878:7878"
    depends_on:
      - db
